### PR TITLE
Label schema

### PR DESCRIPTION
**Pull request by rossf7**
Hey Jose! I saw your tool in Devops Weekly a couple of weeks ago. I really like that it adds labelling to Dockerfiles.

We're working with some folks in the container community (including Gareth Rushgrove) on a standard label schema. To get momentum we want to encourage as many people as possible to label their public images with the org.label-schema namespace.

Once the labels are in place you could use MicroBadger (microbadger.com) to create image badges for jumping between your Docker Image and the appropriate commit on Github.

And if you're interested in getting involved with the label standardization, please jump on in at label-schema.org.

### CODE REVIEW

**Comment by fiunchinho** [comment]
I really like the idea. Thank you!

**Comment by rossf7** [comment]
Thanks for merging!

We're putting together a list of cool labelled images on the microbadger.com home page. Could you push a new version of the image with the build args set? The commit badge should then work and we'd love to feature your image on the site.

**Comment by fiunchinho** [comment]
Pushed! Do you know if is there a way to pass parameters for labels in Dockerhub Automated Builds?

**Comment by rossf7** [comment]
Thanks so much for pushing! Sorry I didn't see about the automated builds. Its not something I've done yet but I'll try and add to our labelling page.

We've updated the website with your image. https://microbadger.com

**Pull request merged**
